# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [1]:
import numpy as np

In [2]:
x = np.random.uniform(0,20,size = (4,7))
x

array([[12.25479791, 16.5014984 ,  6.83518994,  8.18162839,  7.83713861,
         9.9787127 ,  3.95937597],
       [12.24972588,  1.26086726, 14.26131919,  0.26600783, 10.64989999,
         2.02473603,  4.45683621],
       [18.70859437, 18.89233734,  0.34619362,  3.4355657 , 16.12308954,
         3.86680021,  0.40989414],
       [11.85020355, 13.26405191,  6.3645035 ,  2.92762992, 17.77321014,
         6.80272852,  5.49475419]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [3]:
x = np.random.randint(0,10, size = (8,10))
print(x)
a = np.sum(x,axis = 1 )
print(a)
np.argmin(a)

[[7 6 5 6 8 4 5 4 1 9]
 [1 0 5 5 3 1 6 5 9 1]
 [5 4 0 6 0 9 7 9 9 1]
 [2 4 9 2 6 6 2 7 1 9]
 [4 6 1 5 6 4 1 0 0 2]
 [6 8 1 0 0 5 2 1 7 0]
 [1 4 8 6 9 5 7 5 0 2]
 [4 7 0 3 9 1 0 0 3 7]]
[55 36 50 48 29 30 47 34]


4

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [4]:
a,b = np.random.randint(0, 15, size = (1,3)), np.random.randint(0, 15, size = (1,3))
distance = np.linalg.norm(a-b)
distance

19.519221295943137

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [5]:
a = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
b = np.array([[3, -1], [2, 1]])
c = np.array([[7, 21], [11, 8], [8, 4]])
c_neg = c*(-1)
x = np.dot(np.linalg.inv(a), c_neg)
x_final = np.dot(x,  np.linalg.inv(b))
np.trunc(x_final)

array([[ 0.,  0.],
       [-2.,  1.],
       [ 3., -4.]])

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [121]:
import numpy as np

In [122]:
a = np.loadtxt('minutes_n_ingredients.csv',dtype=int, delimiter=',', skiprows=1)
a[0:5,]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]])

 2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [123]:
column1 = a[:,0]
column2 = a[:,1] 
column3 = a[:,2]

In [124]:
#for 2nd column
avg_column2 = np.average(column2)
min_column2 = np.min(column2)
max_column2 = np.max(column2)
median_column2 = np.median(column2)
print('Среднее значение для второго столбца = ', avg_column2, '\nМинимум для второго столбца =', min_column2, '\nМаксимум для второго столбца = ', max_column2, '\nМедиана для второго столбца = ', median_column2)
avg_column2, min_column2, max_column2, median_column2


Среднее значение для второго столбца =  21601.00169 
Минимум для второго столбца = 0 
Максимум для второго столбца =  2147483647 
Медиана для второго столбца =  40.0


(21601.00169, 0, 2147483647, 40.0)

In [125]:
#for 3rd column
avg_column3 = np.average(column3)
min_column3 = np.min(column3)
max_column3 = np.max(column3)
median_column3 = np.median(column3)
print('Среднее значение для третьего столбца = ', avg_column3, '\nМинимум для третьего столбца =', min_column3, '\nМаксимум для третьего столбца = ', max_column3, '\nМедиана для третьего столбца = ', median_column3)


Среднее значение для третьего столбца =  9.05528 
Минимум для третьего столбца = 1 
Максимум для третьего столбца =  39 
Медиана для третьего столбца =  9.0


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [126]:
q = np.quantile(column2, 0.75)
a[:,1] = np.clip(column2, 0, int(q))
column2

array([60, 25, 10, ..., 65,  5, 65])

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [127]:
num_zeros = (column2 == 0).sum()
a[:,1] = np.clip(column2, 1, int(q))
num_zeros, column2

(479, array([60, 25, 10, ..., 65,  5, 65]))

5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [128]:
unique = np.unique(a, axis=1)
len(unique)           

100000

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [129]:
lst = list(column3.copy())
unique = list(set(lst))
frequency = {}
for item in unique:
    frequency[item] = lst.count(item)
print("Всего различных значений кол-ва ингридиентов = ", len(unique),"\nСколько раз встречаются различные значения кол-ва ингридиентов = ", frequency)

Всего различных значений кол-ва ингридиентов =  37 
Сколько раз встречаются различные значения кол-ва ингридиентов =  {1: 13, 2: 926, 3: 2895, 4: 5515, 5: 7913, 6: 9376, 7: 10628, 8: 10951, 9: 10585, 10: 9591, 11: 8297, 12: 6605, 13: 4997, 14: 3663, 15: 2595, 16: 1767, 17: 1246, 18: 790, 19: 573, 20: 376, 21: 217, 22: 161, 23: 105, 24: 69, 25: 50, 26: 28, 27: 16, 28: 16, 29: 12, 30: 12, 31: 3, 32: 1, 33: 2, 34: 1, 35: 3, 37: 1, 39: 1}


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [132]:
not_greater_5 = []
for k in range(0,len(a)):
    if column3[k] <= 5:
        not_greater_5.append(a[k])
not_greater_5 = np.array(not_greater_5)
not_greater_5

array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       ...,
       [ 52088,     60,      5],
       [128811,     15,      4],
       [370915,      5,      4]])

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [133]:
ratio = []
for k in range(1, len(a)):
    ratio.append(column3[k]/column2[k])
print('Максимальное значение = ',max(ratio),'\nСреднее количество ингредиентов на одну минуту для каждого рецепта:',*ratio, sep="\n", end="\n\n")


Максимальное значение = 
24.0

Среднее количество ингредиентов на одну минуту для каждого рецепта:
0.28
0.6
1.2
0.23333333333333334
0.175
0.5
0.3333333333333333
1.2857142857142858
0.35
0.3076923076923077
0.5833333333333334
0.16923076923076924
0.6
0.2
0.6666666666666666
0.5833333333333334
0.1076923076923077
0.2
0.3
0.8
0.16923076923076924
0.09230769230769231
0.16923076923076924
0.11666666666666667
0.27692307692307694
0.15
0.2222222222222222
0.13846153846153847
0.06153846153846154
0.55
0.1076923076923077
0.13846153846153847
0.16923076923076924
0.23333333333333334
0.16923076923076924
0.16923076923076924
0.25
0.15555555555555556
0.4
0.8
0.16
0.32
0.14545454545454545
2.0
0.07272727272727272
0.4
1.0
0.24
0.4
0.45714285714285713
0.5625
0.5333333333333333
0.3
0.2
0.07692307692307693
0.15384615384615385
0.075
0.4
0.07692307692307693
0.15
1.0
0.046153846153846156
0.1076923076923077
0.7
0.16923076923076924
0.2
0.15384615384615385
0.46153846153846156
0.13846153846153847
0.4
0.4
0.3
0.1384615384615

0.2
0.2
0.2
0.225
0.18461538461538463
0.13333333333333333
0.34615384615384615
0.12307692307692308
0.6
0.15384615384615385
0.22
0.07692307692307693
0.7
0.09230769230769231
0.4857142857142857
0.3333333333333333
0.3
0.16
0.15384615384615385
0.6875
0.09230769230769231
0.08571428571428572
0.3
0.18461538461538463
0.4
0.2
0.37037037037037035
0.12307692307692308
0.23076923076923078
0.26
0.2
0.25
0.12
0.09230769230769231
0.52
0.32
0.5142857142857142
0.32
0.5833333333333334
1.0
0.07692307692307693
0.75
0.18461538461538463
0.26666666666666666
0.15384615384615385
0.2
0.2857142857142857
0.55
0.13846153846153847
0.55
2.0
0.16666666666666666
0.36666666666666664
0.5
0.45
0.2833333333333333
0.1076923076923077
0.09230769230769231
0.625
0.3076923076923077
0.2857142857142857
0.26666666666666666
0.26666666666666666
0.26
0.45
0.3333333333333333
0.6
0.28125
0.5
0.12307692307692308
0.8666666666666667
0.15384615384615385
0.3333333333333333
0.2571428571428571
0.2153846153846154
0.35294117647058826
0.4
0.15
0.21

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [134]:
top_100 = a.copy()
top_100 = top_100[top_100[:, 1].argsort()[::-1]][:100]
average_100 = np.average(top_100[:,2])
average_100

9.96

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [135]:
print('   ID     Timing    N_Ingridients')
for m in range(1,11):
    index = np.where(a[:,0] == np.random.choice(column1))
    print(a[index])

   ID     Timing    N_Ingridients
[[71893    60     9]]
[[362717     40     13]]
[[23156    50     9]]
[[59279    25     7]]
[[265014     40     14]]
[[138311     15      5]]
[[463428     10     16]]
[[318687     65      8]]
[[396332     65     10]]
[[110136     25      7]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [136]:
l = 0
for i in range(1,len(a)):
    if column3[i]<avg_column3:
        l+=1
print((l/len(a))*100,'%', sep='')

58.802%


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [239]:
k=0
c = []
simple = a.copy()
for m in range(0, len(a)):
    if simple[m,1] <= 20 and simple[m,2] <=5:
        c.append(1)
        k+=1
    else:
        c.append(0)
simple = np.column_stack((simple,c))
simple

array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [ 81993,     65,     14,      0]])

13. Выведите процент "простых" рецептов в датасете

In [109]:
print(k/len(a)*100,'%', sep='')

9.552%


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [240]:
# короткие = время до,стандартные = время от 10 до 19 минут, длинные = 20+ минут